### ISSUE TITLE
Deprecated classes

### ISSUE THREAD

**Issue by jblankendaal** [effektif/effektif#10]
With the last git pull I did, a lot of the classes in the api that I was using like UserTask & ScriptTask, UserId and TaskService are deprecated (moved to the deprecated package). 
Does this mean that this functionality will be removed, or will this functionality be re-implemented in a different way?

I know this is an alpha release, but hopefully you can give me some insight in the direction Effektif is heading in the (near) future? We are very enthusiastic about the tool so far, but the functionality of for example the scripttask and the usertask in addition to assigning tasks to users is core functionality we (think we) need.

**Comment by tombaeyens** [comment]
We're moving to be the best workflow engine for the cloud.  We want to concentrate first on service orchestration over REST.  An HTTP service invocation is certainly in the scope.  Also the adapter framework to plug in external activity implementations.  Because adapters are connected over REST APIs and webhooks, they can be implemented in any language.

User tasks is  require a lot of infrastructure in terms of identity component, task service etc.  It's looking more likely that user tasks are not in the scope of our open source project.  Keep an eye on the forums and wiki as there we will give an update when we finalized the scope of the project.

I'm curious to learn:
What's your intended use case?
Do you already have an existing task system or identity component that you plan to use?
What did you plan to use for the task UI?

**Comment by jblankendaal** [comment]
Sorry for the late reply, a colleague of my is trying to contact you, we were not hoping on so many changes to the api anymore..... We are looking at throwing out our own (custom made) workflow engine (and possibly replacing it with Effektif).

**Comment by tombaeyens** [comment]
Contact me at my first name at effektif.com

**Comment by jblankendaal** [comment]
Ah, I see Thomas just made a (skype) appointment with him and you for the 12th of may
