### ISSUE TITLE
ExclusiveGateway ends workflow when no transition is found

### ISSUE THREAD

**Issue by jblankendaal** [effektif/effektif#29]
When an exclusive gateway does not have a default transition and no condition is met then the flow ends in the exclusive gateway. The end time of the activityInstance is set and the workstate is removed on the workflowInstance. 
In the code there is a todo for this situation: 
// TODO create an event to let the user decide (ExclusiveGatewayImpl.java, line 69)
A bit further in the code the activityInstance is end()-ed and propagatedToParent().

But since the activityInstance is closed, a message to this workflowInstance is not possible anymore: the workflow is ended.

My proposal is to leave the activityInstance open, so remove the code on lines 75-79. The only thing I am not sure about is what the consequences are when this workflowInstance is part of a invoked flow.

Other thing that I propose is that if no conditions are met and there is no default transition defined, the code also looks for an empty transition, and if found, treats this transition as if it was the default. I already agreed on this in a separate session with @tombaeyens .

I can create the above described patch and do a pull request, I just wanted to consult you guys first.

**Comment by tombaeyens** [comment]
Seems I misinterpreted this issue.  @SilentGert noticed that this is in contradiction with the behavior we need in the product.  In our product we need the activity instance and potentially the workflow instance to end when no outgoing transitions are taken from an exclusive gateway.

Our product is based on the philosophy that if nothing has to be done, then the workflow instance should end.  I'll see if I can refactor this to an overridable method `handleNoTransitions` in the base implementation of exclusive gateway.  That way, you (or we) can override and customize it and use our own customized exclusive gateway instead of the base impl.

I'll fix it.

**Comment by tombaeyens** [comment]
The code had some notes about activity instances that should be kept open.  That I removed.  

I did create a customizable method in case the exclusive gateway is underspecified.  The default implementation will still look for the first transition without a condition.  @SilentGert if that's not ok for you, speak up :)

```
  /** called when this exclusive gateway is 'underspecified' so we have 
   * to guess what's best to do at this point.
   *   
   *  a) there is no outgoing transition with a condition that resolves to true 
   *  b) there is no default transition specified
   *  c) and there is more than 1 transition
   */
  protected TransitionImpl handleUndefinedSelection(ActivityInstanceImpl activityInstance, List<TransitionImpl> outgoingTransitions) {
    return findFirstTransitionWithoutCondition(activityInstance, outgoingTransitions);
  }
```

**Comment by SilentGert** [comment]
In my opinion, if there is no outgoing transition or if no condition matches and there is no default transition defined, the execution of the activity instance should just end. Instead of guessing, which transition might be the correct one, there should be some error log which indicates that no proper transition was found. There shouldn't be any left over open activity instances which prevent the whole workflow instance from finishing, although, there is nothing left to do.

Those issues are the result of an underspecified workflow and, therefore, the user should fix the workflow and configure it properly. The engine in turn shouldn't do too much magic, it will only be harder for a user to understand why the engine behaves in a certain way.

That said, it could be a workaround to use the first transition without a condition if no other could be found. However, this renders the concept of default transitions a bit useless and in the worst case is not predictable, depending on how the outgoing transitions are stored (order might change).

**Comment by jblankendaal** [comment]
Theoretically I agree, but then the engine should complain when deploying the workflow. Now the workflow can be deployed and can run, but workflowInstances can just "die"/end in for example an exclusivegateway and will never be noted again.

**Comment by SilentGert** [comment]
If you argue from that perspective, branches will be executed, which maybe aren't meant to be executed, just because someone forgot to add the respective condition.

**Comment by tombaeyens** [comment]
question is: can we agree on standard behavior for the handleUndefinedSelection method.  the 2 options i see are:  
1) take the first transition without a condition.  and end the execution flow if no such transition is found.
2) end the execution flow anyways.

any other proposal?
if we can agree on the same default, we can put that in the core engine and neither of us has to subclass to customize it.  

my vote goes 1).  and we're 3 so that should give a clear outcome :)

**Comment by SilentGert** [comment]
I vote for 2), the reason being that this kind of error handling doesn't belong into this part of the engine. 
I agree with @jblankendaal that it should be done in an earlier stage, in our case, our product / UI should warn the user.

**Comment by jblankendaal** [comment]
The outcome is clear, unless I have another proposal :)

I see two more options: 
3) Prevent this situation from happening by throwing an error when deploying the workflow where a ExclusiveGateway does not have a default transition. I am not sure if that is possible with the current workflow parsing, but this would be a very nice solution.
4) Leave the workflowInstance in the activity preceding the ExclusiveGateway, either closed or not closed. For sure the workflowInstance should not remain in the Exclusive gateway, since I think the ExclusiveGateway should be stateless...

I vote for option 3)

:)

**Comment by tombaeyens** [comment]
Our authoring does not leverage the engine parsing to detect warnings and errors in the process model.  It's usually easier to build it right into the visual diagram tool, rather then sending the process model to the server, parsing it, sending the errors back and then try to link the errors to the UI elements.

I won't yet actively delete it to give us some more time to reflect.  But I guess there is a big chance that the error capturing part of the parsing will get removed over time.

**Comment by jblankendaal** [comment]
Ok, then I vote for option 1, so it can stay as it is now...
As far as I'm concerned we can close the issue.
